import time
import pandas as pd
import rtamt
import csv
import multiprocessing
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from watchdog.observers import Observer
from watchdog.events import PatternMatchingEventHandler
from pathvalidate import sanitize_filename #https://www.tradingcode.net/python/sanitise-clean-filename/


class Monitor:
    def __init__(self, feed_path, rule_line, stop_event, failure_log, data_dump_log):
        """
        The heart of the run time assurance (rta)
        Many instances (num = # of rules) booted up in parallel inside booter.py

        Responsible for monitoring the feed for robot_states that match its rule
        Feeds matching states through update function which generates robustness values
        Robustness values then get sent to log files (failure_log and/or data_dump_log)
        Robustness values also synchronosouly plotted in plots folder

        feed_path - (string) file path to where the robot state data will come in
        rule - (string), to be popualted in add_rule function, contains the stl rule
        input - (string), to be populated in add_rule function, contains input variables for rule
        output - (string), to be populated in add_rule function, contains output variables for rule
        spec - (rtamt object), used to pass in rule instantiation and updates into rtamt library
        stop_event - internal variable, used for parallel processing, passed through to all classes
        failure_log - (string) file path where to send all stl rule violations
        data_dump_log - (string) file path to where to send all outputed robustness values for stl rules
        fig and graph - just variable substitutes for the typical fig,ax schema, need to make subplots to be able to save graph
        rule_data - (tuple of lists) containing the time and output robustness value for the rule, appended to every time new output is generated by rtamt
        state_data - (dictionary of tuple of lists) ex: {'spd' : ([1,2,3],[4,5,6])} each tuple contains time and signal respectively for each state variable
            used by rule. To be plotted on graphs to help with output robustness analysis

        """
        self.feed_path = feed_path
        self.rule = None
        self.input = None
        self.output = None
        self.spec = None
        self.stop_event = stop_event
        self.failure_log = failure_log
        self.data_dump_log = data_dump_log
        self.fig, self.graph = plt.subplots()
        self.rule_data = ([],[]) # tuple containing x and y values of generated rule robustness
        self.state_data = {} #dictionary containing state datapoints for each variable

        self.add_rule(rule_line)
        self.instantiate_rule()
        self.instantiate_state_data()


    def add_rule(self, line: list):
        """
        Passed through with rule_line variable in init
        line - (list of strings), sent over by booter.py, contains 3 columns for "rule", "input" varibale, and "output" variable

        Indexes into list extracting comonents and setting them to variables, creates empty rtamt instance
        """
        self.rule = line[0]
        self.input = line[1]
        if self.input == '':
            self.input = None
        self.output = line[2]
        self.spec = rtamt.StlDenseTimeSpecification(semantics=rtamt.Semantics.OUTPUT_ROBUSTNESS) #defualt is standard robustness

    def instantiate_rule(self):
        """
        Uses values extracted in add_rule function to set propper parameters
        Then calls standard rtamt functions of parse and pastify to activate rule

        NOTE: pastify is needed to evaluate future timed temporal operators such as "eventually"

        """
        self.spec.declare_var('out', 'float')
        if self.input != None:
            self.spec.declare_var(str(self.input), 'float')
            self.spec.set_var_io_type(str(self.input), 'input')
        if self.output != None:
            self.spec.declare_var(str(self.output), 'float')
            self.spec.set_var_io_type(str(self.output), 'output')

        self.spec.spec = self.rule.strip("'") #removes excess single quotes (') from rule

        try:
            self.spec.parse()
            self.spec.pastify()
        except rtamt.RTAMTException as err:
            print('RTAMT Exception: {}'.format(err))
            sys.exit()
    
    def instantiate_state_data(self):
        """
        Creates empty dictionary of variable states to be plotted on graphs

        """
        for var in [self.input, self.output]:
            if var is not None:
                self.state_data[var] = ([],[])


    def update(self, line: pd.DataFrame):
        """
        Called from the start_overseer function whenever it detected a new line in the feed

        Determines what variables (that exist in this rule) are reported in this new line of data.
        Not all states reported in every line, therefore checks which variables are actually populated
        If any of those variables are populated, extracts their data and appends their values to their respective state data and update instance
        Sends the update instance through the rtamt library
        Upon receiving the output from the rtamt library, if new output robustness values reported,
        Sends the data to the router, appends to the rule_data points, then calls an update on the graphs

        """
        vars_to_update = []
        #Determines which variables are populated
        for var in [self.input, self.output]:
            if var != None:
                if not pd.isna(line.iloc[0][var]):
                    vars_to_update.append(var)
        
        updates = []
        #Updates the variable states dictionary and prepares update message for rtamt
        for var in vars_to_update:
            time = float(line.iloc[0]['time'])
            signal = float(line.iloc[0][var])
            self.state_data[var][0].append(time)
            self.state_data[var][1].append(signal)
            updates.append([var, [[time, signal]]])

        #send the update message into rtamt and receives output
        rob = self.spec.update(*updates)

        #Upon reception, rob will be a list of lists ex: [[5.4, inf], [6.1, -0.7]]
        #List is looped, rule_data points updated, calls update function for graphs
        for i in range(0, len(rob)):
            self.route_data(rob[i])
            self.rule_data[0].append(rob[i][0])
            self.rule_data[1].append(rob[i][1])
            self.update_graph()

    def route_data(self, output):
        """
        Called from the update function, responsible for sending data to logs
        output - singular output robustness result ex: [5.4, inf]

        Determines whether the output robustness value represents a violation
        If so, sends data the failure_log as well

        """
        time = output[0]
        robustness = output[1]
        if robustness < 0:
            with open (self.failure_log, mode='a') as f:
                writer = csv.writer(f)
                writer.writerow([self.rule, time, robustness])
        with open(self.data_dump_log, mode='a') as f:
            writer = csv.writer(f)
            writer.writerow([self.rule, time, robustness])

    def update_graph(self):
        """
        Called from the udpate function, resposnsible for updating the graphs

        Clears the current graphs to force an update and repopulates them
        """
        self.graph.clear()
        #Step functions, to accurately represent the assumption of constant signal until reported otherwise
        self.graph.step(*self.rule_data, where='post', label = 'Rule Output Robustness')
        for var in self.state_data:
            #Loads in rule variables state data to assist with validation
            self.graph.step(*self.state_data[var], where='post', label = f'{var}', alpha=0.5)

        #Shading logic, used to represent the infinities given by output robustness (aka when a rule is vacously true)
        start_shading = None
        for (x,y) in zip(self.rule_data[0], self.rule_data[1]):
            if y == float('inf') and start_shading is None:
                start_shading = x
            elif y != float('inf') and start_shading is not None:
                self.graph.axvspan(start_shading, x, color='gray', alpha=0.25)
                start_shading = None

        #Includes grid, title, legend, and centers the graph
        self.graph.grid(True, which='both')
        self.graph.set_title(f"Rule: {self.rule}", wrap=True)
        self.graph.axhline(y=0, color='k')
        self.graph.axvline(x=0, color='k')
        self.graph.legend()
        plt.tight_layout()
        #Saves the graph name based on rule, uses 3rd party library for text cleaning: https://www.tradingcode.net/python/sanitise-clean-filename/
        clean_name = sanitize_filename(self.rule, replacement_text="_")
        self.fig.savefig(f"plots/{clean_name}.png")

    def start_overseer(self):
        """
        Called by the activate function, responsible for montioring the feed, and reporting when updates has occured

        Contains internal functions (count_lines and on_modified) responsible for determining when an actual update has occurred and trigger update function
        Creates and activates an Observer, which waits until the stop_event is "set" before terminating

        Inspirationd drawn from the following sources:
        https://stackoverflow.com/questions/62412482/how-to-monitor-a-csv-file-for-changes
        https://www.geeksforgeeks.org/python/create-a-watchdog-in-python-to-look-for-filesystem-changes/

        """
        current_lines = 0

        #Called by event handler when Observer is triggered
        #If the trigger was because there is a new line (i.e more lines than previosuly counted), call update function
        def on_modified(event):
            cur_iter = count_lines()
            nonlocal current_lines
            if cur_iter > current_lines:
                current_lines = cur_iter
                df = pd.read_csv(event.src_path)
                if current_lines != 1: #Skips the header
                    self.update(df[-1:])
        
        #Counts the number of lines in the csv, used to determine if an update actually occurred
        def count_lines():
            total=0
            with open('feed.csv', 'r') as f:
                for line in f:
                    total+=1
            return total

        #Creates the event handler and links to the on_modified function
        event_handler = PatternMatchingEventHandler(patterns=['feed.csv'], ignore_patterns=[], ignore_directories=True, case_sensitive=True)
        event_handler.on_modified = on_modified

        #Instnatiates the observer and starts a new thread for it
        #Waits for stop_event to be triggered, then shutsdown
        observer = Observer()
        observer.schedule(event_handler, path=".", recursive=False)
        observer.start()

        self.stop_event.wait()
        observer.stop()
        observer.join()

    def activate(self):
        """
        Activation function, called from booter.py by each thread to start the observer
        """
        self.start_overseer()



if __name__ == "__main__":
    """
    Sample setup to be run with 'python monitor.py' from terminal
    NOTE: will not do anything because the feed, will not be automaitcally updating, must copy paste line by line to see process
    
    """
    stop_event = multiprocessing.Event()
    with open ("./logs/failure_log.csv", mode='w') as f:
        writer = csv.writer(f)
        writer.writerow(["Rule", "Time_of_Violation", "Severity"])
    with open("./logs/data_dump_log.csv", mode='w') as f:
        writer = csv.writer(f)
        writer.writerow(["Rule", "Time", "Roboustness"])
    m = Monitor('feed.csv', ['out = (spd < 5);',None, 'spd'], stop_event, "./logs/failure_log.csv", "./logs/data_dump_log.csv")
    # m = Monitor('feed.csv', ['out = ((srf < 0) implies eventually[0:5] (srf > 0));',None,'srf'], stop_event, "./logs/failure_log.csv", "./logs/data_dump_log.csv")
    m.activate()
    time.sleep(15)
    stop_event.set()