# linear and angular speed limits for the robot
turtle:
  max_v: 0.1 # m/s
  max_w: 0.2 # rad/s
  image_topic: "/turtle1/image_compressed"
  waypoint_topic: "/turtle1/waypoint"
  reached_goal_topic: "/turtle1/topoplan/reached_goal"
  sampled_actions_topic: "/turtle1/sampled_actions"
  vel_topic: "/turtle1/cmd_vel"
  overlay_topic: "/turtle1/turtlelay"
ghost:
  max_v: 0.2 # m/s
  max_w: 0.3 # rad/s
  image_topic: "/camera/camera/color/image_raw/compressed"
#  image_topic: "/camera/camera/color/image_raw"
  waypoint_topic: "/ghost/waypoint"
  reached_goal_topic: "/ghost/topoplan/reached_goal"
  sampled_actions_topic: "/ghost/sampled_actions"
  vel_topic: "  /mcu/command/manual_twist"
  overlay_topic: "/ghost/path_overlay"
  img_w: 1280
  img_h: 720
# observation rate fo the robot
frame_rate: 15