import sys
import csv
import rtamt
import os
import re
import argparse
import matplotlib.pyplot as plt
from pathlib import Path

from rtamt.spec.stl.discrete_time.specification import Semantics


class Runtime_Assurance:
    def __init__(self, rule_path):
        self.rule_path = rule_path

    def _instantiate_rule(self, spec, rule:str, i:str, o:str):
        """
        Takes in a pointer to spec object
        Takes in rule in string form
        Takes input variable if any
        Takes output variable if any

        Instantiates Spec object with rule parameters
        """
        spec.declare_var('out', 'float')
        if len(i) != 0:
            spec.declare_var(str(i), 'float')
            spec.set_var_io_type(str(i), 'input')
        if len(o) != 0:
            spec.declare_var(str(o), 'float')
            spec.set_var_io_type(str(o), 'output')

        spec.spec = rule.strip("'")
    
    def _process_rule(self, spec):
        "Activates Rule through rtamt architecture"
        try:
            spec.parse()
        except rtamt.RTAMTException as err:
            print('RTAMT Exception: {}'.format(err))
            sys.exit()


    def _read_data_csv(self, file_path):
        """
        Reads csv at file path
        Returns Dictionary of key: list[values]
        """
        f = open(file_path, 'r')
        reader = csv.reader(f)
    
        headers = next(reader, None)
        dict_columns = {}
        for h in headers:
            dict_columns[h] = []

        for row in reader:
            for h, v in zip(headers, row):
                dict_columns[h].append(float(v))

        return dict_columns

    def _evaluate_rule(self, spec, data_path:str, i:str, o:str) -> list:
        """
        spec - rtamt object
        data_path - file path to data for specific rule
        i - input variables for rule
        o - output varaibles for rule

        Reads in provided variable data
        Evaluates with rtamt object
        
        Returns output object
        """
        data = self._read_data_csv(data_path)
        data_keys = ['time', i, o]
        # print("***THE DATA*****")
        # print(data)
        metrics = {k: data[k] for k in data_keys if len(k) != 0}
        return spec.evaluate(metrics)

    def _plot_rule(self, rob, rule, data_path):
        """
        Plots the output data generated by the rule
        """
        print('Output Robustness: {}'.format(rob))
        time = []
        output_robustness = []
        for e in rob:
            time.append(e[0])
            output_robustness.append(e[1])

        fig, ax = plt.subplots()
        ax.plot(time, output_robustness)
        # ax.set_aspect('equal')
        ax.grid(True, which='both')
        ax.set_title(f"Rule: {rule}", wrap=True)
        ax.axhline(y=0, color='k')
        ax.axvline(x=0, color='k')
        plt.tight_layout()
        fig.savefig(f"runtime_sample_states/plots/{Path(data_path).stem}.png")


    def run(self):
        """
        Main runner function for the class
        """
        with open(self.rule_path, mode='r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                spec = rtamt.StlDiscreteTimeSpecification(semantics=rtamt.Semantics.OUTPUT_ROBUSTNESS)
                self._instantiate_rule(spec, row['rule'], row['input'], row['output'])
                # print("Am I getting to here succesfully?")
                print(f"The Rule: {row['rule']}")
                print(f"Inputs: {row['input']}")
                print(f"Outputs: {row['output']}")
                self._process_rule(spec)
                # print("but I am guessing not here")
                rob = self._evaluate_rule(spec, row['data_path'], row['input'], row['output'])
                self._plot_rule(rob, row['rule'], row['data_path'])



if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Runner for Runtime_Assurance Class")
    p.add_argument("rule_file_location", type=str, help="Path to rules.csv file")
    args = p.parse_args()
    ra = Runtime_Assurance(args.rule_file_location)
    ra.run()



